const express = require('express')
const router = express.Router()
const salesRoutes = require('./sales.routes')
const authRoutes = require('./auth.routes')
const employeesRoutes = require('./employees.routes')
const rolesRoutes = require('./roles.routes')
const permissionsRoutes = require('./permissions.routes')
const expensesRoutes = require('./expenses.routes')
const inventoryRoutes = require('./inventory.routes')
const supplierRoutes = require('./supplier.routes')
const dashboardRoutes = require('./dashboard.routes')
const customersRoutes = require('./customers.routes')
const reportsRoutes = require('./reports.routes')

//importacion de rutas
router.use('/auth', authRoutes)
router.use('/dashboard', dashboardRoutes)
router.use('/employees', employeesRoutes)
router.use('/expenses', expensesRoutes)
router.use('/inventory', inventoryRoutes)
router.use('/suppliers', supplierRoutes)
router.use('/customers', customersRoutes)
router.use('/reports', reportsRoutes)
router.use('/sales', salesRoutes)
router.use('/roles', rolesRoutes)
router.use('/permissions', permissionsRoutes)

module.exports = router
